# Generated by Django 5.0.6 on 2024-11-20 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira_app.employeedetails')),
            ],
        ),
    ]
