# Generated by Django 5.0.6 on 2024-11-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_data',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Manager'), ('3', 'Employee')], default=3, max_length=10),
        ),
    ]
