# Generated by Django 5.0.6 on 2024-11-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_app', '0002_employeelogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
