# Generated by Django 5.0.6 on 2024-11-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_app', '0002_alter_customuser_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_data',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Manager'), ('3', 'Employee')], default=1, max_length=10),
        ),
    ]
