# Generated by Django 5.0.6 on 2024-11-20 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_app', '0003_alter_employeedetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='department_id',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.DO_NOTHING, to='jira_app.departmentdetails'),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='role',
            field=models.CharField(max_length=25),
        ),
    ]
