# Generated by Django 5.0.6 on 2024-11-20 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_app', '0004_alter_employeedetails_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jira_app.departmentdetails'),
        ),
    ]
