# Generated by Django 5.0.6 on 2024-11-20 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_app', '0005_alter_employeedetails_department_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jira_app.projectdetails'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jira_app.clientdetails'),
        ),
    ]
