# Generated by Django 5.0.6 on 2024-11-20 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_app', '0007_alter_employeedetails_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelogin',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jira_app.employeedetails'),
        ),
    ]
