# Generated by Django 5.0.6 on 2024-11-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_app', '0008_alter_employeelogin_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelogin',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
